"""empty message

Revision ID: 065da80dc3f1
Revises: a864b046d08e
Create Date: 2024-08-21 15:34:03.642709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065da80dc3f1'
down_revision = 'a864b046d08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('hl_ms_excel_variables', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel_variables', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('hl_ms_excel', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
