"""empty message

Revision ID: 0d1316045668
Revises: 6d4e9cd8f3af
Create Date: 2024-10-14 10:58:46.164519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d1316045668'
down_revision = '6d4e9cd8f3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dl_ms_equipment')
    op.drop_table('dl_ms_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_ms_category',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nama Category'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dl_ms_category_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('dl_ms_equipment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True, comment='ref to id table ini sendiri (recursive)'),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nama Equipment'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Deskripsi Equipment'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['dl_ms_category.id'], name='dl_ms_equipment_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['dl_ms_equipment.id'], name='dl_ms_equipment_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dl_ms_equipment_pkey')
    )
    # ### end Alembic commands ###
