"""empty message

Revision ID: 19848be3511f
Revises: 2c15583e293a
Create Date: 2024-09-27 10:29:42.609326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19848be3511f'
down_revision = '2c15583e293a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel_variables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_nphr', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_over_haul', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('web_id', sa.String(length=255), nullable=True, comment='PI Web ID'))
        batch_op.alter_column('input_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel_variables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.VARCHAR(length=155), autoincrement=False, nullable=True))
        batch_op.alter_column('input_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('web_id')
        batch_op.drop_column('is_over_haul')
        batch_op.drop_column('is_nphr')

    op.create_table('m_params',
    sa.Column('kode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keterangan', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
