"""empty message

Revision ID: 1326608983ca
Revises: 
Create Date: 2024-08-27 15:25:20.890216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1326608983ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_mr_resource',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_mr_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hl_ms_excel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('excel_filename', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('excel_filename')
    )
    op.create_table('hl_ms_masterdata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kode', sa.String(length=300), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_mr_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=300), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('position', sa.String(length=300), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth_mr_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('users_name_email_username_idx', 'auth_mr_user', ['name', 'email', 'username'], unique=False)
    op.create_table('auth_tr_role_resource',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['auth_mr_resource.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth_mr_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hl_ms_excel_variables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('excel_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('input_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=155), nullable=True),
    sa.Column('excel_variable_name', sa.String(length=500), nullable=True),
    sa.Column('satuan', sa.String(length=50), nullable=True),
    sa.Column('in_out', sa.String(length=25), nullable=True),
    sa.Column('is_pareto', sa.Boolean(), nullable=True),
    sa.Column('is_faktor_koreksi', sa.Boolean(), nullable=True),
    sa.Column('is_nilai_losses', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['excel_id'], ['hl_ms_excel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hl_tr_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('periode', sa.Date(), nullable=False),
    sa.Column('jenis_parameter', sa.String(length=300), nullable=False),
    sa.Column('excel_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['excel_id'], ['hl_ms_excel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hl_ms_excel_variables_cause',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='ref to id table ini sendiri (recursive)'),
    sa.Column('variable_id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['hl_ms_excel_variables_cause.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['hl_ms_excel_variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hl_ms_excel_variables_header',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variable_id'], ['hl_ms_excel_variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hl_tr_data_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=False),
    sa.Column('efficiency_transaction_id', sa.UUID(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=True),
    sa.Column('nilai_string', sa.String(length=255), nullable=True),
    sa.Column('persen_hr', sa.Float(), nullable=False),
    sa.Column('deviasi', sa.Float(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['efficiency_transaction_id'], ['hl_tr_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['hl_ms_excel_variables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hl_tr_data_detail_root_cause',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_detail_id', sa.UUID(), nullable=True, comment='Ref to hl_tr_data_detail'),
    sa.Column('cause_id', sa.UUID(), nullable=True, comment='Ref to hl_m_cause 1 to many'),
    sa.Column('is_repair', sa.Boolean(), nullable=True, comment='1=ya, 0=tidak'),
    sa.Column('biaya', sa.Float(), nullable=True, comment='Besar Biaya yang dikeluarkan (input)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('variable_header_value', sa.JSON(), nullable=True, comment="[{id: 9, nama: 'sdasdas asdasd', val: 1}]"),
    sa.ForeignKeyConstraint(['cause_id'], ['hl_ms_excel_variables_cause.id'], ),
    sa.ForeignKeyConstraint(['data_detail_id'], ['hl_tr_data_detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hl_tr_data_detail_root_cause')
    op.drop_table('hl_tr_data_detail')
    op.drop_table('hl_ms_excel_variables_header')
    op.drop_table('hl_ms_excel_variables_cause')
    op.drop_table('hl_tr_data')
    op.drop_table('hl_ms_excel_variables')
    op.drop_table('auth_tr_role_resource')
    op.drop_index('users_name_email_username_idx', table_name='auth_mr_user')
    op.drop_table('auth_mr_user')
    op.drop_table('hl_ms_masterdata')
    op.drop_table('hl_ms_excel')
    op.drop_table('auth_mr_role')
    op.drop_table('auth_mr_resource')
    # ### end Alembic commands ###
