"""empty message

Revision ID: 20a89302a28e
Revises: 9f6f3d230a8b
Create Date: 2024-09-12 13:53:45.971948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a89302a28e'
down_revision = '9f6f3d230a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persen_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.drop_column('persen_threshold')

    # ### end Alembic commands ###
