"""empty message

Revision ID: 23d30a1414d1
Revises: 7f05bf45aef6
Create Date: 2024-08-19 12:43:36.710432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d30a1414d1'
down_revision = '7f05bf45aef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('excels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('src', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('src')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit')
    )
    op.create_table('variables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('excels_id', sa.UUID(), nullable=True),
    sa.Column('variable', sa.String(length=300), nullable=False),
    sa.Column('data_location', sa.String(length=300), nullable=False),
    sa.Column('units_id', sa.UUID(), nullable=True),
    sa.Column('base_case', sa.String(length=300), nullable=False),
    sa.Column('variable_type', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['excels_id'], ['excels.id'], ),
    sa.ForeignKeyConstraint(['units_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_location'),
    sa.UniqueConstraint('variable')
    )
    op.create_table('case_inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cases_id', sa.UUID(), nullable=True),
    sa.Column('variables_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cases_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['variables_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cases_id'),
    sa.UniqueConstraint('variables_id')
    )
    op.create_table('case_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cases_id', sa.UUID(), nullable=True),
    sa.Column('variables_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cases_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['variables_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cases_id'),
    sa.UniqueConstraint('variables_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_outputs')
    op.drop_table('case_inputs')
    op.drop_table('variables')
    op.drop_table('units')
    op.drop_table('excels')
    op.drop_table('cases')
    # ### end Alembic commands ###
