"""empty message

Revision ID: 2bbb3c578bca
Revises: 5df2883e1e52
Create Date: 2024-10-17 16:36:09.334566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bbb3c578bca'
down_revision = '5df2883e1e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_fft_fetch',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['dl_ms_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dl_fft_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_fft_value',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['dl_ms_tag.id'], name='dl_fft_value_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dl_fft_value_pkey')
    )
    op.drop_table('dl_fft_fetch')
    # ### end Alembic commands ###
