"""empty message

Revision ID: 36d2d345d2f1
Revises: 39b1a379771e
Create Date: 2024-10-29 16:29:29.350540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d2d345d2f1'
down_revision = '39b1a379771e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dl_wo_staging', schema=None) as batch_op:
        batch_op.alter_column('time_to_event',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dl_wo_staging', schema=None) as batch_op:
        batch_op.alter_column('time_to_event',
               existing_type=sa.Text(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
