"""empty message

Revision ID: 42d66222c365
Revises: 20a89302a28e
Create Date: 2024-09-24 09:52:18.391022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d66222c365'
down_revision = '20a89302a28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pfi_ms_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama Equipment'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pfi_ms_tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('web_id', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('path', sa.String(length=150), nullable=False),
    sa.Column('descriptor', sa.String(length=150), nullable=True),
    sa.Column('point_class', sa.String(length=15), nullable=True),
    sa.Column('point_type', sa.String(length=15), nullable=True),
    sa.Column('digital_set_name', sa.String(length=150), nullable=True),
    sa.Column('engineering_units', sa.String(length=15), nullable=True),
    sa.Column('span', sa.Integer(), nullable=True),
    sa.Column('zero', sa.Integer(), nullable=True),
    sa.Column('step', sa.Boolean(), nullable=True),
    sa.Column('future', sa.Boolean(), nullable=True),
    sa.Column('display_digits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pfi_ms_equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='ref to id table ini sendiri (recursive)'),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama Equipment'),
    sa.Column('description', sa.Text(), nullable=True, comment='Deskripsi Equipment'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['pfi_ms_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['pfi_ms_equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pfi_value_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=True, comment='ref to id table ini sendiri (recursive)'),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('units_abbreviation', sa.String(length=15), nullable=False),
    sa.Column('good', sa.Boolean(), nullable=False),
    sa.Column('questionable', sa.Boolean(), nullable=False),
    sa.Column('substituted', sa.Boolean(), nullable=False),
    sa.Column('annotated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['pfi_ms_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_mr_user', schema=None) as batch_op:
        batch_op.drop_index('users_name_email_username_idx')

    op.drop_table('pfi_value_tag')
    op.drop_table('pfi_ms_equipment')
    op.drop_table('pfi_ms_tag')
    op.drop_table('pfi_ms_category')
    # ### end Alembic commands ###
