"""empty message

Revision ID: 4a459a41bad5
Revises: ca48c3412e6c
Create Date: 2024-09-04 16:30:15.985174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a459a41bad5'
down_revision = 'ca48c3412e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=300), nullable=False))
        batch_op.alter_column('periode',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.alter_column('periode',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('name')
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
