"""empty message

Revision ID: 5a6c58c6a4aa
Revises: 661004f14640
Create Date: 2024-10-29 09:41:37.113345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a6c58c6a4aa'
down_revision = '661004f14640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dl_wo_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actstart_olah', sa.DateTime(), nullable=True))
        batch_op.drop_column('acstart_olah')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dl_wo_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acstart_olah', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('actstart_olah')

    # ### end Alembic commands ###
