"""empty message

Revision ID: 6037ce1d576d
Revises: 0a9c7ef369b1
Create Date: 2024-11-04 09:38:26.222353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6037ce1d576d'
down_revision = '0a9c7ef369b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_psd_value_temp',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('psd_value', sa.Float(), nullable=True),
    sa.Column('total_value_1', sa.Float(), nullable=True),
    sa.Column('total_value_2', sa.Float(), nullable=True),
    sa.Column('total_value_3', sa.Float(), nullable=True),
    sa.Column('max_value_1', sa.Float(), nullable=True),
    sa.Column('max_value_2', sa.Float(), nullable=True),
    sa.Column('max_value_3', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['dl_ms_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dl_fft_fetch_temp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_fft_fetch_temp',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['dl_ms_tag.id'], name='dl_fft_fetch_temp_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dl_fft_fetch_temp_pkey')
    )
    op.drop_table('dl_psd_value_temp')
    # ### end Alembic commands ###
