"""empty message

Revision ID: 6d4e9cd8f3af
Revises: edab98c802ad
Create Date: 2024-10-14 10:57:45.857201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4e9cd8f3af'
down_revision = 'edab98c802ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_fft_fetch',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('units_abbreviation', sa.String(length=15), nullable=False),
    sa.Column('good', sa.Boolean(), nullable=False),
    sa.Column('questionable', sa.Boolean(), nullable=False),
    sa.Column('substituted', sa.Boolean(), nullable=False),
    sa.Column('annotated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['dl_ms_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dl_fft_fetch')
    # ### end Alembic commands ###
