"""empty message

Revision ID: 70d9ec8e81f6
Revises: 7068db379583
Create Date: 2024-08-26 14:15:37.386390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d9ec8e81f6'
down_revision = '7068db379583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
