"""empty message

Revision ID: 75a51adfe70b
Revises: 1cd16b00a79f
Create Date: 2024-10-02 09:38:03.192498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75a51adfe70b'
down_revision = '1cd16b00a79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_ms_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama Category'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dl_ms_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('web_id', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('path', sa.String(length=150), nullable=False),
    sa.Column('descriptor', sa.String(length=150), nullable=True),
    sa.Column('point_class', sa.String(length=15), nullable=True),
    sa.Column('point_type', sa.String(length=15), nullable=True),
    sa.Column('digital_set_name', sa.String(length=150), nullable=True),
    sa.Column('engineering_units', sa.String(length=15), nullable=True),
    sa.Column('span', sa.Integer(), nullable=True),
    sa.Column('zero', sa.Integer(), nullable=True),
    sa.Column('step', sa.Boolean(), nullable=True),
    sa.Column('future', sa.Boolean(), nullable=True),
    sa.Column('display_digits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dl_ms_equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='ref to id table ini sendiri (recursive)'),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama Equipment'),
    sa.Column('description', sa.Text(), nullable=True, comment='Deskripsi Equipment'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['dl_ms_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['dl_ms_equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dl_value_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('units_abbreviation', sa.String(length=15), nullable=False),
    sa.Column('good', sa.Boolean(), nullable=False),
    sa.Column('questionable', sa.Boolean(), nullable=False),
    sa.Column('substituted', sa.Boolean(), nullable=False),
    sa.Column('annotated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['dl_ms_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pfi_ms_equipment')
    op.drop_table('pfi_ms_category')
    op.drop_table('pfi_value_tag')
    op.drop_table('pfi_ms_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pfi_ms_tag',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('pfi_ms_tag_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('web_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('descriptor', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('point_class', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('point_type', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('digital_set_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('engineering_units', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('span', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('future', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_digits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pfi_ms_tag_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pfi_value_tag',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('units_abbreviation', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('good', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('questionable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('substituted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('annotated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['pfi_ms_tag.id'], name='pfi_value_tag_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pfi_value_tag_pkey')
    )
    op.create_table('pfi_ms_category',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nama Category'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pfi_ms_category_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pfi_ms_equipment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True, comment='ref to id table ini sendiri (recursive)'),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nama Equipment'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Deskripsi Equipment'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['pfi_ms_category.id'], name='pfi_ms_equipment_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['pfi_ms_equipment.id'], name='pfi_ms_equipment_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pfi_ms_equipment_pkey')
    )
    op.drop_table('dl_value_tag')
    op.drop_table('dl_ms_equipment')
    op.drop_table('dl_ms_tag')
    op.drop_table('dl_ms_category')
    # ### end Alembic commands ###
