"""empty message

Revision ID: 7f993aeaf5fd
Revises: 0477ca51a61b
Create Date: 2024-09-24 17:10:58.880278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f993aeaf5fd'
down_revision = '0477ca51a61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_performance_test', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_perfomance_test')

    with op.batch_alter_table('pfi_ms_category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nama Category',
               existing_comment='Nama Equipment',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pfi_ms_category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               comment='Nama Equipment',
               existing_comment='Nama Category',
               existing_nullable=False)

    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_perfomance_test', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_performance_test')

    # ### end Alembic commands ###
