"""empty message

Revision ID: 98d0c33803c2
Revises: 0b8a366fe546
Create Date: 2024-08-27 11:30:31.223743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d0c33803c2'
down_revision = '0b8a366fe546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nilai_string', sa.String(length=255), nullable=True))
        batch_op.alter_column('nilai',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data_detail', schema=None) as batch_op:
        batch_op.alter_column('nilai',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('nilai_string')

    # ### end Alembic commands ###
