"""empty message

Revision ID: a864b046d08e
Revises: 572ae8b88f8a
Create Date: 2024-08-21 14:46:34.640695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a864b046d08e'
down_revision = '572ae8b88f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=300), nullable=False))
        batch_op.drop_constraint('users_position_id_fkey', type_='foreignkey')
        batch_op.drop_column('position_id')
    op.drop_table('positions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_position_id_fkey', 'positions', ['position_id'], ['id'])
        batch_op.drop_column('position')

    op.create_table('positions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='positions_pkey')
    )
    # ### end Alembic commands ###
