"""empty message

Revision ID: a909e1057cc7
Revises: fd909fe01f21
Create Date: 2024-10-01 16:13:03.752851

"""
import datetime
import uuid
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a909e1057cc7'
down_revision = 'fd909fe01f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('hl_ms_thermoflow_status',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('is_running', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    # Insert initial data into the new table
    op.bulk_insert(
        table,
        [
            {
                'id': uuid.uuid4(),  # Generate a new UUID
                'is_running': False,  # Set initial state
                'created_at': datetime.datetime.now(),  # Set creation timestamp
                'updated_at': None  # No update timestamp initially
            }
        ]
    )

    op.create_table('hl_tr_thermoflow_log',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('efficiency_transaction_id',
                              sa.UUID(), nullable=False),
                    sa.Column('status', sa.String(length=300), nullable=False),
                    sa.Column('error_message', sa.String(
                        length=300), nullable=True),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['efficiency_transaction_id'], [
                        'hl_tr_data.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hl_tr_thermoflow_log')
    op.drop_table('hl_ms_thermoflow_status')
    # ### end Alembic commands ###
