"""empty message

Revision ID: b10a82ac25f0
Revises: edbc52a20b52
Create Date: 2024-08-22 11:34:29.546227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10a82ac25f0'
down_revision = 'edbc52a20b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hl_tr_data_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=False),
    sa.Column('efficiency_transaction_id', sa.UUID(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('persen_hr', sa.Float(), nullable=False),
    sa.Column('deviasi', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['efficiency_transaction_id'], ['hl_tr_data.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['hl_ms_excel_variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hl_tr_data_detail')
    # ### end Alembic commands ###
