"""empty message

Revision ID: becb70a4e6e4
Revises: 42d66222c365
Create Date: 2024-09-24 14:06:59.589914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becb70a4e6e4'
down_revision = '42d66222c365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_perfomance_test', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('performance_test_weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.drop_column('performance_test_weight')
        batch_op.drop_column('is_perfomance_test')

    # ### end Alembic commands ###
