"""empty message

Revision ID: bfa5855a792a
Revises: 36d2d345d2f1
Create Date: 2024-10-31 13:31:08.356346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa5855a792a'
down_revision = '36d2d345d2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_value_tag_temp',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('units_abbreviation', sa.String(length=15), nullable=False),
    sa.Column('good', sa.Boolean(), nullable=False),
    sa.Column('questionable', sa.Boolean(), nullable=False),
    sa.Column('substituted', sa.Boolean(), nullable=False),
    sa.Column('annotated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['dl_ms_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dl_value_tag_temp')
    # ### end Alembic commands ###
