"""empty message

Revision ID: ca48c3412e6c
Revises: 58ea8e043348
Create Date: 2024-08-29 13:27:15.311500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca48c3412e6c'
down_revision = '58ea8e043348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel_variables_cause', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.drop_column('nama')

    with op.batch_alter_table('hl_ms_excel_variables_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.drop_column('nama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel_variables_header', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('hl_ms_excel_variables_cause', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
