"""empty message

Revision ID: d88fff05e183
Revises: 7d79783df4cc
Create Date: 2024-08-21 09:45:47.004412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = 'd88fff05e183'
down_revision = '7d79783df4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hl_ms_masterdata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kode', sa.String(length=300), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # Bulk insert initial data
    op.bulk_insert(
        sa.table(
            'hl_ms_masterdata',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('name', sa.String(length=300), nullable=False),
            sa.Column('kode', sa.String(length=300), nullable=True),
            sa.Column('seq', sa.Integer(), nullable=True),
            sa.Column('group_id', sa.String(length=300), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
            sa.Column('updated_at', sa.DateTime(), nullable=True)
        ),
        [
            {'id': str(uuid.uuid4()), 'name': 'Target', 'kode': 'Target', 'seq': 100, 'group_id': 'data.jenis_parameters'},
            {'id': str(uuid.uuid4()), 'name': 'KPI_Tahunan', 'kode': 'KPI_Tahunan', 'seq': 200, 'group_id': 'data.jenis_parameters'},
            {'id': str(uuid.uuid4()), 'name': 'Current', 'kode': 'Current', 'seq': 300, 'group_id': 'data.jenis_parameters'},
        ]
    )
    
    op.create_table('hl_ms_excel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('excel_filename', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('excel_filename')
    )
    op.create_table('hl_ms_excel_variables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('excel_id', sa.UUID(), nullable=False),
    sa.Column('input_name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=155), nullable=True),
    sa.Column('satuan', sa.String(length=50), nullable=True),
    sa.Column('in_out', sa.String(length=25), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['excel_id'], ['hl_ms_excel.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hl_tr_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('periode', sa.Date(), nullable=False),
    sa.Column('jenis_parameter', sa.String(length=300), nullable=False),
    sa.Column('excel_id', sa.UUID(), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['excel_id'], ['hl_ms_excel.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['hl_ms_excel_variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('case_inputs')
    op.drop_table('case_outputs')
    op.drop_table('variables')
    op.drop_table('excels')
    op.drop_table('units')
    op.drop_table('cases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cases_pkey'),
    sa.UniqueConstraint('name', name='cases_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('case_outputs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cases_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('variables_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cases_id'], ['cases.id'], name='case_outputs_cases_id_fkey'),
    sa.ForeignKeyConstraint(['variables_id'], ['variables.id'], name='case_outputs_variables_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='case_outputs_pkey')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='units_pkey'),
    sa.UniqueConstraint('unit', name='units_unit_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('variables',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('excels_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('variable', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('data_location', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('units_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('base_case', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('variable_type', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excels_id'], ['excels.id'], name='variables_excels_id_fkey'),
    sa.ForeignKeyConstraint(['units_id'], ['units.id'], name='variables_units_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='variables_pkey'),
    sa.UniqueConstraint('data_location', name='variables_data_location_key'),
    sa.UniqueConstraint('variable', name='variables_variable_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('case_inputs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cases_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('variables_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cases_id'], ['cases.id'], name='case_inputs_cases_id_fkey'),
    sa.ForeignKeyConstraint(['variables_id'], ['variables.id'], name='case_inputs_variables_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='case_inputs_pkey')
    )
    op.create_table('excels',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('src', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='excels_pkey'),
    sa.UniqueConstraint('name', name='excels_name_key'),
    sa.UniqueConstraint('src', name='excels_src_key')
    )
    op.drop_table('hl_tr_data')
    op.drop_table('hl_ms_excel_variables')
    op.drop_table('hl_ms_excel')
    op.drop_table('hl_ms_masterdata')
    # ### end Alembic commands ###
