"""empty message

Revision ID: dd2a2df18045
Revises: be5a743a3861
Create Date: 2024-10-29 09:11:38.717449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2a2df18045'
down_revision = 'be5a743a3861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dl_wo_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description2', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dl_wo_staging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('description2')
        batch_op.drop_column('description1')

    # ### end Alembic commands ###
