"""empty message

Revision ID: 572ae8b88f8a
Revises: d88fff05e183
Create Date: 2024-08-21 14:12:59.368742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572ae8b88f8a'
down_revision = 'd88fff05e183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint('hl_ms_excel_updated_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('hl_ms_excel_created_by_fkey', type_='foreignkey')

    with op.batch_alter_table('hl_ms_excel_variables', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint('hl_ms_excel_variables_created_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('hl_ms_excel_variables_updated_by_fkey', type_='foreignkey')

    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint('hl_tr_data_updated_by_fkey', type_='foreignkey')
        batch_op.drop_constraint('hl_tr_data_created_by_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.create_foreign_key('hl_tr_data_created_by_fkey', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('hl_tr_data_updated_by_fkey', 'users', ['updated_by'], ['id'])
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('hl_ms_excel_variables', schema=None) as batch_op:
        batch_op.create_foreign_key('hl_ms_excel_variables_updated_by_fkey', 'users', ['updated_by'], ['id'])
        batch_op.create_foreign_key('hl_ms_excel_variables_created_by_fkey', 'users', ['created_by'], ['id'])
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('hl_ms_excel', schema=None) as batch_op:
        batch_op.create_foreign_key('hl_ms_excel_created_by_fkey', 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key('hl_ms_excel_updated_by_fkey', 'users', ['updated_by'], ['id'])
        batch_op.alter_column('updated_by',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
