"""empty message

Revision ID: 7068db379583
Revises: a9166b92ebb4
Create Date: 2024-08-26 14:06:00.221115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7068db379583'
down_revision = 'a9166b92ebb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel', schema=None) as batch_op:
        batch_op.create_index('ix_excel_filename', ['excel_filename'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel', schema=None) as batch_op:
        batch_op.drop_index('ix_excel_filename')

    # ### end Alembic commands ###
